### ISSUE TITLE
Command 'interactive' does not work

### ISSUE THREAD

**Issue by nemethf** [NetSys/bess#335]
It seems some part of #24 hasn't been pulled correctly. 
Reapplying the following hunk of @MurphyMc, the problem disappears.
```
diff --git a/bessctl/cli.py b/bessctl/cli.py
index 2ea19a2..6d58b98 100644
--- a/bessctl/cli.py
+++ b/bessctl/cli.py
@@ -34,7 +34,16 @@ class CLI(object):
         self.last_cmd = ''

         self.interactive = interactive
-        if not interactive:
+        self.rl = None
+
+        self.maybe_go_interactive()
+
+    def maybe_go_interactive(self):
+        if self.interactive: return
+
+        self.interactive = self.fin.isatty() and self.fout.isatty()
+
+        if not self.interactive:
             self.rl = None
             return
```

without the patch:
```
 ./bessctl interactive
Traceback (most recent call last):
  File "./bessctl", line 202, in <module>
    run_cmds(cStringIO.StringIO('\n'.join(cmds)))
  File "./bessctl", line 178, in run_cmds
    cli.loop()
  File "./bessctl", line 112, in loop
    super(BESSCLI, self).loop()
  File "/export/netsys/src/bess/bessctl/cli.py", line 452, in loop
    self.process_one_line()
  File "/export/netsys/src/bess/bessctl/cli.py", line 394, in process_one_line
    self.call_func(func, args)
  File "./bessctl", line 64, in call_func
    super(BESSCLI, self).call_func(func, args)
  File "/export/netsys/src/bess/bessctl/cli.py", line 369, in call_func
    func(*args)
  File "/export/netsys/src/bess/bessctl/commands.py", line 1532, in interactive
    cli.maybe_go_interactive()
AttributeError: 'BESSCLI' object has no attribute 'maybe_go_interactive'
```

with the patch:
```
$ ./bessctl interactive
Type "help" for more information.
localhost:10514 $ 
```
or in more useful example:
```
$ ./bessctl show pipeline -- interactive
+-------------------+                      +----------+                      +-------------------+
|     port_inc0     |                      | macswap0 |                      |     port_out0     |
|      PortInc      |  :0 52231913504 0:   | MACSwap  |  :0 52231718560 0:   |      PortOut      |
| pmd_port0/PMDPort | -------------------> |          | -------------------> | pmd_port0/PMDPort |
+-------------------+                      +----------+                      +-------------------+
Type "help" for more information.
localhost:10514 $
```

**Comment by nemethf** [comment]
on the other hand, the patch in my original comment breaks readline support :(

**Comment by justinemarie** [comment]
Hi Felicián!
You shouldn't need to pass a flag to run bessctl in interactive mode, it should enter interactive mode by default (ie., just type `./bessctl`, no flags). Does this solve your problem or are you worried about something in addition to that?
Thanks for the post!
Justine

**Comment by MurphyMc** [comment]
This looks like a regression introduced by ab80210c7882d67bcec033404da96c34e9bcc4bc.

What breaks about readline support, Felicián?  Or breaks it relative to what?  Running without the "interactive" command?  It certainly looks like it might take a little work to integrate the colored output from ab80210c7882d67bcec033404da96c34e9bcc4bc with the "interactive" command added in #24, though it seems like it should be doable.

Another option would be to just remove the "interactive" command, but I thought it had legit use cases, which is why I added it. :)  As described in its commit message (ab42dbc612201208b04357fe811cd92f9b48db2a), the idea is that you can use it to get bessctl in interactive mode, but having run some other commands via the commandline first.  I don't remember the exact scenario I had at the time, but it's stuff along the lines of using the bessctl commandline to set the daemon host/port if it's not the default before dropping into interactive.  Useful for scripts or just to keep in your commandline history if you keep wanting to connect to different daemons... without requiring that you enter commands in the CLI every time.

**Comment by justinemarie** [comment]
Ah, I see, you wanted to do something like `./bessctl daemon start -- run perftest/pktgen -- interactive`. This is equivalent to `./bessctl daemon start -- run perftest/pktgen; ./bessctl` but lets you do it all in one line. So we want this feature back?

**Comment by MurphyMc** [comment]
I certainly would.  It actually breaks one of my projects -- I just hadn't noticed yet.  In the example you show, two commands are fine.  But unless there is a new way to set the daemon address from the commandline... the type of scenario I describe is still problematic (since setting the daemon for the first invocation doesn't help for the second!).

My project isn't open sourced yet, so I obviously can't expect anyone else to care.  At some point when I have more time, I'd be willing to fix it myself and offer a patch (or would plead for equivalent functionality), but it's not vital to me at the moment, so I don't have a timeline.

**Comment by justinemarie** [comment]
It looks like a quick fix -- I'll take a look at it tomorrow or Monday :-)

**Comment by MurphyMc** [comment]
Yeah, I agree, it looks quick.  Just splitting it back into a helper (maybe_go_interactive), I think?  That'd be great; thanks, Justine!

(Though I still don't know what aspect of readline breaks under this scenario.  Hopefully @nemethf can clarify.  It may just be something to do with applying that chunk from my old patch without really integrating it into Sangjin's new code in ab80210c7882d67bcec033404da96c34e9bcc4bc.)

**Comment by nemethf** [comment]
I admit that this is a minor issue, but it inexplicably annoyed me, so I dug a little bit deeper. 

 `__main__` of bessctl calls `run_cli()` if there are no command line arguments, otherwise it calls `run_cmds()`.  However, only `run_cli()` sets the history_file.  So if we go interactive from the command-line, then pressing the up arrow won't show previous commands.

Thank you both.

(By the way, is there a mailing list or forum where bess related questions can be discussed?)

**Comment by justinemarie** [comment]
Instead of a mailing list, we use the GitHub issue tracker (at least for now). You can somehow tell GitHub to subscribe to updates -- I get emails whenever anyone posts. 

Are there non-issue use cases we should consider using a mailing list for? One thing I could think of is to announce "major release versions..."

**Comment by justinemarie** [comment]
Re: history -- so there are two issues, (1) Make the "interactive" command start interactive mode, and (2) Make non-interactive commands get logged to history.

**Comment by MurphyMc** [comment]
Ah, so readline isn't broken, it's just that the history file never gets set.  Makes sense.

It seems like there may be a similar issue with color not working if you get to the commandline via "interactive" too, since it looks like some of that is set in run_cli() too.  Probably nothing that a little refactoring wouldn't fix.  (Though for my part, having the interactive command work at all is much more important than having color/history work right.)

**Comment by justinemarie** [comment]
Working on a patch as we speak, interactive works, color works, history still now for some reason...

**Comment by justinemarie** [comment]
Stay tuned...

**Comment by MurphyMc** [comment]
Thanks, Justine!  (et al.)
