### PR TITLE
Updates DPDK to 19.11

### LINKED ISSUE #921: [DPDK]: Enable use of newer version
Tried to build BESS with 19.05. Pasting the errors below

```
Generating protobuf codes for pybess...
Building BESS daemon...
Log:
 make: Entering directory '/build/bess/bess/core'
[CXX]       packet_pool.o
[DRIVER_CXX] drivers/pmd.o
packet_pool.cc: In constructor 'bess::PlainPacketPool::PlainPacketPool(size_t, int)':
packet_pool.cc:173:17: error: 'rte_mempool_xmem_size' was not declared in this scope
   size_t size = rte_mempool_xmem_size(pool_->size, element_size, page_shift,
                 ^~~~~~~~~~~~~~~~~~~~~
packet_pool.cc:173:17: note: suggested alternative: 'rte_mempool_mem_iter'
   size_t size = rte_mempool_xmem_size(pool_->size, element_size, page_shift,
                 ^~~~~~~~~~~~~~~~~~~~~
                 rte_mempool_mem_iter
packet_pool.cc: In constructor 'bess::BessPacketPool::BessPacketPool(size_t, int)':
packet_pool.cc:207:9: error: 'rte_mempool_xmem_size' was not declared in this scope
         rte_mempool_xmem_size(deficit, element_size, page_shift, pool_->flags);
         ^~~~~~~~~~~~~~~~~~~~~
packet_pool.cc:207:9: note: suggested alternative: 'rte_mempool_mem_iter'
         rte_mempool_xmem_size(deficit, element_size, page_shift, pool_->flags);
         ^~~~~~~~~~~~~~~~~~~~~
         rte_mempool_mem_iter
In file included from drivers/pmd.cc:33:0:
/root/dpdk/build/include/rte_ethdev_pci.h: In function 'int eth_dev_pci_specific_init(rte_eth_dev*, void*)':
/root/dpdk/build/include/rte_ethdev_pci.h:75:35: error: invalid conversion from 'void*' to 'rte_pci_device*' [-fpermissive]
  struct rte_pci_device *pci_dev = bus_device;
                                   ^~~~~~~~~~
drivers/pmd.cc: In function 'const rte_eth_conf default_eth_conf()':
drivers/pmd.cc:51:14: error: 'struct rte_eth_rxmode' has no member named 'ignore_offload_bitfield'
   ret.rxmode.ignore_offload_bitfield = 1;
              ^~~~~~~~~~~~~~~~~~~~~~~
drivers/pmd.cc:52:26: error: 'DEV_RX_OFFLOAD_CRC_STRIP' was not declared in this scope
   ret.rxmode.offloads |= DEV_RX_OFFLOAD_CRC_STRIP;
                          ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/pmd.cc:52:26: note: suggested alternative: 'DEV_RX_OFFLOAD_MACSEC_STRIP'
   ret.rxmode.offloads |= DEV_RX_OFFLOAD_CRC_STRIP;
                          ^~~~~~~~~~~~~~~~~~~~~~~~
                          DEV_RX_OFFLOAD_MACSEC_STRIP
drivers/pmd.cc: In member function 'virtual void PMDPort::InitDriver()':
drivers/pmd.cc:66:50: warning: 'uint16_t rte_eth_dev_count()' is deprecated [-Wdeprecated-declarations]
   dpdk_port_t num_dpdk_ports = rte_eth_dev_count();
                                                  ^
In file included from drivers/pmd.h:38:0,
                 from drivers/pmd.cc:31:
/root/dpdk/build/include/rte_ethdev.h:1593:10: note: declared here
 uint16_t rte_eth_dev_count(void);
          ^~~~~~~~~~~~~~~~~
drivers/pmd.cc:79:18: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
     if (dev_info.pci_dev) {
                  ^~~~~~~
drivers/pmd.cc:82:20: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
           dev_info.pci_dev->addr.domain, dev_info.pci_dev->addr.bus,
                    ^~~~~~~
drivers/pmd.cc:82:51: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
           dev_info.pci_dev->addr.domain, dev_info.pci_dev->addr.bus,
                                                   ^~~~~~~
drivers/pmd.cc:83:20: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
           dev_info.pci_dev->addr.devid, dev_info.pci_dev->addr.function,
                    ^~~~~~~
drivers/pmd.cc:83:50: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
           dev_info.pci_dev->addr.devid, dev_info.pci_dev->addr.function,
                                                  ^~~~~~~
drivers/pmd.cc:84:20: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
           dev_info.pci_dev->id.vendor_id, dev_info.pci_dev->id.device_id);
                    ^~~~~~~
drivers/pmd.cc:84:52: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
           dev_info.pci_dev->id.vendor_id, dev_info.pci_dev->id.device_id);
                                                    ^~~~~~~
drivers/pmd.cc: In function 'CommandResponse find_dpdk_port_by_pci_addr(const string&, dpdk_port_t*, bool*)':
drivers/pmd.cc:136:50: warning: 'uint16_t rte_eth_dev_count()' is deprecated [-Wdeprecated-declarations]
   dpdk_port_t num_dpdk_ports = rte_eth_dev_count();
                                                  ^
In file included from drivers/pmd.h:38:0,
                 from drivers/pmd.cc:31:
/root/dpdk/build/include/rte_ethdev.h:1593:10: note: declared here
 uint16_t rte_eth_dev_count(void);
          ^~~~~~~~~~~~~~~~~
drivers/pmd.cc:141:18: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
     if (dev_info.pci_dev) {
                  ^~~~~~~
drivers/pmd.cc:142:53: error: 'struct rte_eth_dev_info' has no member named 'pci_dev'
       if (rte_eal_compare_pci_addr(&addr, &dev_info.pci_dev->addr) == 0) {
                                                     ^~~~~~~
drivers/pmd.cc:156:11: error: 'rte_eth_dev_attach' was not declared in this scope
     ret = rte_eth_dev_attach(name, &port_id);
           ^~~~~~~~~~~~~~~~~~
drivers/pmd.cc:156:11: note: suggested alternative: 'rte_eth_dev_data'
     ret = rte_eth_dev_attach(name, &port_id);
           ^~~~~~~~~~~~~~~~~~
           rte_eth_dev_data
drivers/pmd.cc: In function 'CommandResponse find_dpdk_vdev(const string&, dpdk_port_t*, bool*)':
drivers/pmd.cc:184:13: error: 'rte_eth_dev_attach' was not declared in this scope
   int ret = rte_eth_dev_attach(name, &port_id);
             ^~~~~~~~~~~~~~~~~~
drivers/pmd.cc:184:13: note: suggested alternative: 'rte_eth_dev_data'
   int ret = rte_eth_dev_attach(name, &port_id);
             ^~~~~~~~~~~~~~~~~~
             rte_eth_dev_data
drivers/pmd.cc: In member function 'CommandResponse PMDPort::Init(const bess::pb::PMDPortArg&)':
drivers/pmd.cc:259:14: error: 'struct rte_eth_txconf' has no member named 'txq_flags'
   eth_txconf.txq_flags = ETH_TXQ_FLAGS_NOVLANOFFL |
              ^~~~~~~~~
drivers/pmd.cc:259:26: error: 'ETH_TXQ_FLAGS_NOVLANOFFL' was not declared in this scope
   eth_txconf.txq_flags = ETH_TXQ_FLAGS_NOVLANOFFL |
                          ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/pmd.cc:259:26: note: suggested alternative: '_IO_FLAGS2_NOTCANCEL'
   eth_txconf.txq_flags = ETH_TXQ_FLAGS_NOVLANOFFL |
                          ^~~~~~~~~~~~~~~~~~~~~~~~
                          _IO_FLAGS2_NOTCANCEL
drivers/pmd.cc:260:26: error: 'ETH_TXQ_FLAGS_NOMULTSEGS' was not declared in this scope
                          ETH_TXQ_FLAGS_NOMULTSEGS * (1 - SN_TSO_SG) |
                          ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/pmd.cc:260:26: note: suggested alternative: 'RTE_CPUFLAG_NUMFLAGS'
                          ETH_TXQ_FLAGS_NOMULTSEGS * (1 - SN_TSO_SG) |
                          ^~~~~~~~~~~~~~~~~~~~~~~~
                          RTE_CPUFLAG_NUMFLAGS
drivers/pmd.cc:261:26: error: 'ETH_TXQ_FLAGS_NOXSUMS' was not declared in this scope
                          ETH_TXQ_FLAGS_NOXSUMS * (1 - SN_HW_TXCSUM);
                          ^~~~~~~~~~~~~~~~~~~~~
drivers/pmd.cc: In member function 'virtual void PMDPort::DeInit()':
drivers/pmd.cc:375:11: error: 'rte_eth_dev_detach' was not declared in this scope
     ret = rte_eth_dev_detach(dpdk_port_id_, name);
           ^~~~~~~~~~~~~~~~~~
drivers/pmd.cc:375:11: note: suggested alternative: 'rte_eth_dev_data'
     ret = rte_eth_dev_detach(dpdk_port_id_, name);
           ^~~~~~~~~~~~~~~~~~
           rte_eth_dev_data
Error: [0;31mpacket_pool.o
[0;33mg++ -o packet_pool.o -c packet_pool.cc -std=c++17 -g3 -ggdb3 -march=native -isystem /root/dpdk/build/include -isystem /build/bess/bess/core -isystem ./.. -isystem /build/bess/bess/core/modules -D_GNU_SOURCE -Werror -Wall -Wextra -Wcast-align -Wno-error=deprecated-declarations -pthread -I/usr/include/x86_64-linux-gnu -fno-gnu-unique -O3 -DNDEBUG -MT packet_pool.o -MMD -MP -MF .deps/packet_pool.d[0m
Makefile:439: recipe for target 'packet_pool.o' failed
make: *** [packet_pool.o] Error 1
make: *** Waiting for unfinished jobs....
Error: [0;31mdrivers/pmd.o
[0;33mg++ -o drivers/pmd.o -c drivers/pmd.cc -std=c++17 -g3 -ggdb3 -march=native -isystem /root/dpdk/build/include -isystem /build/bess/bess/core -isystem drivers/.. -isystem /build/bess/bess/core/modules -D_GNU_SOURCE -Werror -Wall -Wextra -Wcast-align -Wno-error=deprecated-declarations -pthread -I/usr/include/x86_64-linux-gnu -fno-gnu-unique -O3 -DNDEBUG -MT drivers/pmd.o -MMD -MP -MF .deps/drivers/pmd.d[0m
Makefile:391: recipe for target 'drivers/pmd.o' failed
make: *** [drivers/pmd.o] Error 1
make: Leaving directory '/build/bess/bess/core'

Error has occured running command: make -j88 -C core
```

### PR DESCRIPTION
**Pull request by trozet**
Also sets RSS HW offload flags based on device info and RX queues
configured rather than assuming all flags are supported. This fixes an
issue with setting invalid flags on XL710 NICs.

Closes #921

Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
Adding PCI based PMDPort works, need to test vdev and traffic.

**Comment by trozet** [comment]
tcp_flow_reconstruct_test is failing because PacketPool is segfaulting during call to : rte_mempool_op_calc_mem_size_default

https://gist.githubusercontent.com/trozet/d7a35edac02e6b29881d5907f8c03c8b/raw/b930c42f18f758546196fa3faad63dc529f8ac46/gistfile1.txt

@sangjinhan  do you mind taking a look at the above please?

**Comment by trozet** [comment]
@sangjinhan nvm it should be fixed now. New error that I will look at tmrw:

/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libpcap.a(bpf_filter.o): In function `bpf_validate':
(.text+0x520): multiple definition of `bpf_validate'
/build/bess/deps/dpdk-19.08/build/lib/librte_bpf.a(bpf_validate.o):/build/bess/deps/dpdk-19.08/lib/librte_bpf/bpf_validate.c:2213: first defined here

**Comment by krsna1729** [comment]
DPDK LTS 19.11 released today. Tried this PR (DPDK compiled separately). Needed minor changes shown below

https://doc.dpdk.org/guides/rel_notes/release_19_11.html#api-changes
https://doc.dpdk.org/guides/rel_notes/release_19_11.html#new-features

```diff
diff --git a/core/drivers/pmd.cc b/core/drivers/pmd.cc
index 3ed68315..1c31efdc 100644
--- a/core/drivers/pmd.cc
+++ b/core/drivers/pmd.cc
@@ -126,8 +126,7 @@ static CommandResponse find_dpdk_port_by_pci_addr(const std::string &pci,
     return CommandFailure(EINVAL, "No PCI address specified");
   }
 
-  if (eal_parse_pci_DomBDF(pci.c_str(), &addr) != 0 &&
-      eal_parse_pci_BDF(pci.c_str(), &addr) != 0) {
+  if (rte_pci_addr_parse(pci.c_str(), &addr) != 0) {
     return CommandFailure(EINVAL,
                           "PCI address must be like "
                           "dddd:bb:dd.ff or bb:dd.ff");
@@ -139,7 +138,7 @@ static CommandResponse find_dpdk_port_by_pci_addr(const std::string &pci,
     rte_eth_dev_info_get(i, &dev_info);
 
     if (dev_info.pci_dev) {
-      if (rte_eal_compare_pci_addr(&addr, &dev_info.pci_dev->addr) == 0) {
+      if (rte_pci_addr_cmp(&addr, &dev_info.pci_dev->addr) == 0) {
         port_id = i;
         break;
       }
diff --git a/core/packet_pool.cc b/core/packet_pool.cc
index 7318cee6..e08c99cc 100644
--- a/core/packet_pool.cc
+++ b/core/packet_pool.cc
@@ -147,7 +147,8 @@ bool PacketPool::AllocBulk(Packet **pkts, size_t count, size_t len) {
 void PacketPool::PostPopulate() {
   PoolPrivate priv = {
       .dpdk_priv = {.mbuf_data_room_size = SNBUF_HEADROOM + SNBUF_DATA,
-                    .mbuf_priv_size = SNBUF_RESERVE},
+                    .mbuf_priv_size = SNBUF_RESERVE,
+                    .flags = 0},
       .owner = this};
 
   rte_pktmbuf_pool_init(pool_, &priv.dpdk_priv);
```

**Comment by trozet** [comment]
Thanks @krsna1729! Will update the PR to 19.11 with your changes.

**Comment by trozet** [comment]
1 case failed on clang 6. It might be transient. Worth re-running travis I think

[----------] 1 test from ProcessCommandLineArgs
[ RUN      ] ProcessCommandLineArgs.DumpTypes
bessd_test.cc:148: Failure
Death test: ProcessCommandLineArgs()
    Result: died but not with expected exit code:
            Exited with exit status 1
Actual msg:
[  DEATH   ] AddressSanitizer:DEADLYSIGNAL
[  DEATH   ] 
[  FAILED  ] ProcessCommandLineArgs.DumpTypes (92 ms)

**Comment by sangjinhan** [comment]
Thank you very much for doing this. Please don't worry about the address sanitizer error. It seems to have nothing to do with this PR (other PRs are having the same problem). I am looking into the issue.

**Comment by krsna1729** [comment]
@sangjinhan

**Comment by melvinw** [comment]
Superseded by #965. Thanks again for doing this!
